### PR TITLE
Improved design

### PR DESCRIPTION
**Pull request by magsout**
capture d ecran 2016-08-25 a 10 38 42

### CODE REVIEW

**Comment by miketaylr** [comment]
ooooo

**Comment by miketaylr** [comment]
I think @karlcow was wanting to do an iteration of design as well. Thoughts?

Personally I really dig this (I mean, the intial design _was_ perfect).

**Comment by magsout** [comment]
@miketaylr yeah ok, ping my lovely dear @karlcow

**Comment by karlcow** [comment]
ahah. Action Item. Done. 
One less thing to do. :) Thanks @magsout ❤️ 
I can erase compat-dashboard and its modules directory :D

**Comment by miketaylr** [comment]
❤️

**Pull request merged**
